CREATE TABLE CLIENTE (
	CPF CHAR(11) NOT NULL,
 	RG CHAR(20) NOT NULL,
 	Nome_cliente CHAR(80) NOT NULL,
Celular_cliente CHAR(20),
 	Telefone_cliente CHAR(20),
 	Email_cliente CHAR(80),
 	Renda_Mensal FLOAT,
 	Limite_Credito FLOAT,
 	Data_Nascimento DATE,
 	Observacoes VARCHAR(500),
CONSTRAINT PRK_CLIENTE PRIMARY KEY(CPF)
);
CREATE INDEX indice_nome ON CLIENTE(Nome_cliente);


CREATE TABLE FUNCIONARIO(
Codigo_Funcionario CHAR(20) NOT NULL,
Nome_funcionario CHAR(80) NOT NULL,
Cargo CHAR(20) NOT NULL,
Senha CHAR(20) NOT NULL,
Email_funcionario CHAR(80) NOT NULL,
Telefone_funcionario CHAR(20),
Celular_funcionario CHAR(20) NOT NULL,
CONSTRAINT PRK_FUNCIONARIO PRIMARY KEY(Codigo_Funcionario)
);
CREATE INDEX indice_nome_funcionario ON FUNCIONARIO(Nome_funcionario);


CREATE TABLE PRODUTO(
Codigo_Produto INTEGER NOT NULL,
 Nome_descricao VARCHAR(80) NOT NULL,
Tipo_Produto CHAR(50) NOT NULL,
Unidade CHAR(12) NOT NULL,
Qtd_Estoque INTEGER NOT NULL,
Preco_Entrada FLOAT NOT NULL,
Preco_Venda FLOAT NOT NULL,
Aliquota_ICMS FLOAT NOT NULL,
observacoes VARCHAR(500),
CONSTRAINT PRK_PRODUTO PRIMARY KEY(Codigo_Produto )
);
CREATE INDEX indice_nome_descricao ON PRODUTO(Nome_descricao);


CREATE TABLE ENDERECO(
Id_Endereco INTEGER NOT NULL,
CEP CHAR(10) NOT NULL,
Cidade VARCHAR(50) NOT NULL,
UF CHAR(2) NOT NULL,
Bairro VARCHAR(50) NOT NULL,
Logradouro VARCHAR(50),
Complemento 	VARCHAR(100),
CONSTRAINT PRK_ENDERECO PRIMARY KEY(Id_Endereco)
);



CREATE TABLE NOTA_ENTRADA(
Id_Nota_Entrada INTEGER NOT NULL,
Data_Emissao DATE NOT NULL,
Valor_Total FLOAT NOT NULL,
CNPJ_Fornecedor CHAR(20) NOT NULL,
CONSTRAINT PRK_NOTA_ENTRADA PRIMARY KEY(Id_Nota_Entrada)
);


CREATE TABLE MUX_ENDERECO(
Id_Endereco INTEGER NOT NULL,
CPF CHAR(11) NOT NULL,
CONSTRAINT PRK_MUX_ENDERECO PRIMARY KEY(Id_Endereco, CPF),
CONSTRAINT FRK_MUX_ENDERECO_id_endereco FOREIGN KEY(Id_Endereco) REFERENCES ENDERECO(Id_Endereco),
CONSTRAINT FRK_MUX_ENDERECO_cpf FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF)
);


CREATE TABLE NOTA_DE_SAIDA(
Id_Nota_Saida INTEGER NOT NULL,
CPF CHAR(11) NOT NULL,
Codigo_Funcionario CHAR(20) NOT NULL,
Valor_Total FLOAT NOT NULL,
Data DATE NOT NULL,
Hora CHAR(6) NOT NULL,
Forma_pagamento CHAR(20) NOT NULL,
Status_Pagamento CHAR(1) NOT NULL,
CONSTRAINT PRK_NOTA_DE_SAIDA PRIMARY KEY(Id_Nota_saida),
CONSTRAINT FRK_NOTA_DE_SAIDA_CPF FOREIGN KEY(CPF) REFERENCES CLIENTE(CPF),
CONSTRAINT FRK_NOTA_DE_SAIDA_Codigo_Funcionario FOREIGN KEY(Codigo_Funcionario ) REFERENCES FUNCIONARIO(Codigo_Funcionario )
);


CREATE TABLE ITEM_SAIDA(
Id_Item_saida INTEGER NOT NULL,
Codigo_Produto INTEGER NOT NULL,
Id_Nota_Saida INTEGER NOT NULL,
Qtd_Vendida INTEGER NOT NULL,
Desconto FLOAT NOT NULL,
Valor FLOAT NOT NULL,
CONSTRAINT PRK_ITEM_SAIDA PRIMARY KEY(Id_Item_saida ),
CONSTRAINT FRK_ITEM_SAIDA_Codigo_Produto  FOREIGN KEY(Codigo_Produto ) REFERENCES PRODUTO(Codigo_Produto),
CONSTRAINT FRK_ITEM_SAIDA_Id_Nota_Saida   FOREIGN KEY(Id_Nota_Saida) REFERENCES NOTA_DE_SAIDA(Id_Nota_Saida)
);


CREATE TABLE ITEM_ENTRADA(
Id_Item_entrada INTEGER NOT NULL,
Id_Nota_Entrada INTEGER NOT NULL,
Codigo_Produto INTEGER NOT NULL,
Preco_Entrada FLOAT NOT NULL,
Qtd INTEGER NOT NULL,
CONSTRAINT PRK_ITEM_ENTRADA PRIMARY KEY(Id_Item_entrada),
CONSTRAINT FRK_ITEM_ENTRADA_Codigo_Produto  FOREIGN KEY(Codigo_Produto) REFERENCES PRODUTO(Codigo_Produto),
CONSTRAINT FRK_ITEM_ENTRADA_Id_Nota_Entrada   FOREIGN KEY(Id_Nota_Entrada ) REFERENCES NOTA_ENTRADA(Id_Nota_Entrada)
);
